---
title: "tt_august2724"
author: "Havisha Khurana"
date: "2024-08-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
library(stringr)
library(forcats)
library(purrr)
library(tidyr)
library(tm)
library(showtext)
```

```{r}
power_rangers_episodes <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-08-27/power_rangers_episodes.csv')

font_add_google("Open Sans", "os")
showtext_auto()
```

I want to get which characters were named in each of the episode description and then make a plot. To identify characters, I will look for words starting with capital letters.

```{r}
remove_words <- c("meanwhile", "earth", "dr", "ms", "mr", "mrs", "",
                  "angel", "grove", "master", "command", "spd", "spds", 
                  "time", "org", "prince", "force", "center","can")

character_appearance <- power_rangers_episodes %>%
  arrange(air_date) %>%
  mutate(seq = row_number()) %>%
  rowwise() %>%
  mutate(
    words = str_split(desc, pattern = " "),
    cap_words = reduce(words[grepl("^[A-Z]", words)], paste, sep = ";")
  ) %>%
  ungroup() %>%
  separate_longer_delim(cap_words, delim = ";") %>%
  select(season_title, episode_num, cap_words, seq) %>%
  distinct() %>%
  mutate(
    cap_words = removePunctuation(cap_words),
    cap_words = tolower(cap_words), 
    cap_words = if_else(cap_words %in% c("ranger","power"), "rangers", cap_words)
  ) %>%
  filter(!cap_words %in% c(stopwords("english"), remove_words)) %>%
  mutate(cap_words = str_to_title(cap_words),
         cap_words = ifelse(cap_words == "TJ", "T.J.", cap_words),
         cap_words = ifelse(cap_words %in% c("Lord","Zedd"), "Lord Zedd", cap_words),
         cap_words = ifelse(cap_words %in% c("Dai","Shi"), "Dai Shi", cap_words),
         cap_words = ifelse(cap_words == "Ritas", "Rita", cap_words)) %>%
  distinct() %>%
  group_by(cap_words) %>%
  mutate(
    occurence = n()
    #cap_words = fct_reorder(cap_words, -occurence)
  ) %>%
  ungroup()

season_seq <- character_appearance %>%
  group_by(season_title) %>%
  summarize(
    episode_seq = min(seq)
  ) %>%
  arrange(episode_seq) %>%
  mutate(season_label = row_number(),
         seaoson_label = ifelse(season_label == 1, "Season 1", as.character(season_label)))

color_seq <- rep(c(RColorBrewer::brewer.pal(8, "Pastel2"), RColorBrewer::brewer.pal(9, "Pastel1")), 2)
```


```{r}
character_mention_plot <- character_appearance %>%
  filter(occurence > 14)  %>%
  ggplot() +
  geom_point(aes(y = fct_reorder(cap_words, occurence), x = seq, 
                 color = season_title, 
                 shape = 108,
                 size = 20
                 ),
             show.legend = F)+
  scale_shape_identity()+
  scale_x_continuous(expand = c(0,0),
                     breaks = season_seq$episode_seq,
                     labels = season_seq$seaoson_label,
                     sec.axis = dup_axis())+
  #scale_y_discrete(sec.axis = dup_axis())+
  labs(
    y = "",
    x = "",
    title = "Top Character Mentions in Power Rangers Episode Descriptions",
    subtitle = "Rangers get the most mentions across seasons,\nfollowed by lead seasonal villian, like Rita and Zedd.",
    caption = "Source: Power Rangers data curated by Nikita K.\nShowing characters with at least 15 mentions across 921 episodes; colors differentiate seasons."
  )+
  scale_color_manual(values = color_seq)+
  #theme_minimal()+
  theme(
    text = element_text(family = "os", color = "ivory"),
    plot.title = element_text(hjust = 0.5, face = "bold",
                              lineheight = 0.3, size = 32),
    plot.subtitle = element_text(hjust = 0.5, face = "italic",
                                 lineheight = 0.3, size = 28),
    plot.caption = element_text(face = "italic",
                                 lineheight = 0.3, size = 20),
    panel.grid = element_blank(),
    axis.text = element_text(color = "ivory3", size = 20),
    axis.ticks.x = element_line(color = "ivory3"),
    panel.background = element_rect(fill = "#3A3A3A"),
    plot.background = element_rect(fill = "#3A3A3A", color = "transparent")
    # panel.background = element_rect(fill = "#F5F5F5"),
    # plot.background = element_rect(fill = "#F5F5F5")
  )
character_mention_plot
```

```{r}
ggsave(here::here("products/tt_aug2724_power_rangers_character_mentions.jpeg"),
       height = 5, width = 6)
```

