---
title: "tt_2024-07-16"
author: "Havisha Khurana"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load library
library(tidyverse)
library(gganimate)

# load data
# Clean data provided by the [English Womens Football (EWF)
# Database](https://github.com/probjects/ewf-database). No cleaning was
# necessary, but the files were resaved to simplify the csvs.
ewf_appearances <- readr::read_csv(
  "https://raw.githubusercontent.com/probjects/ewf-database/main/data/ewf_appearances.csv"
)

# ewf_matches <- readr::read_csv(
#   "https://raw.githubusercontent.com/probjects/ewf-database/main/data/ewf_matches.csv"
# )
# 
# ewf_standings <- readr::read_csv(
#   "https://raw.githubusercontent.com/probjects/ewf-database/main/data/ewf_standings.csv"
# )
```

<!-- ## Teams that played the highest matches overall -->

```{r}
# ewf_appearances <- ewf_appearances %>%
#     mutate(format = grepl("WSL", division),
#            season_name = ifelse(format == TRUE, paste0("WSL ", parse_number(season)),
#                                 paste0("Championships ", parse_number(season))),
#            format = factor(format, levels = c(TRUE, FALSE), 
#                            labels = c("League", "Championships"))) 
# 
# ewf_appearances %>%
#     filter(format == "League") %>%
#     group_by(team_name) %>%
#     summarize(
#         total = n()) %>%
#     ggplot(aes(y = fct_reorder(team_name, total), x = total)) +
#     geom_col(fill = "darkgreen") +
#     #facet_wrap(~format, ncol = 1, drop = T) +
#     theme_classic() 
# 
# ewf_appearances %>%
#     filter(format == "Championships") %>%
#     group_by(team_name) %>%
#     summarize(
#         total = n()) %>%
#     ggplot(aes(y = fct_reorder(team_name, total), x = total)) +
#     geom_col(fill = "darkgreen") +
    #facet_wrap(~format, ncol = 1, drop = T) +
    theme_classic() 

    #     loss = sum(loss, na.rm = T),
    #     draw = sum(draw, na.rm = T),
    #     win_home = sum(home_team & win, na.rm = T),
    #     win_away = sum(away_team & win, na.rm = T)
    # ) %>%
    # mutate(across(loss:win_away, ~.x/total)) %>%
    # pivot_longer(
    #     cols = loss:win_away,
    #     names_to = "outcome",
    #     values_to = "matches"
    # ) %>%
    # ggplot(aes(y = team_name, x = matches, fill = outcome)) +
    # geom_col()+
    # facet_wrap(~season_id)
```


## Teams that won the most matches by year in WSL League Tier 1

```{r}
wins_most_year <- ewf_appearances %>%
    filter(format == "League", tier == 1) %>%
    mutate(season_name = ifelse(grepl("Spring", division), 
                                paste0("WSL Spring ", parse_number(season)),
                                season_name)) %>%
    group_by(team_name, season_id, season_name) %>%
    summarize(
        total_wins = sum(win)) %>%
    group_by(season_id) %>%
    mutate(rank = rank(total_wins, ties.method = "random")) %>%
    filter(rank <=8) %>%
    arrange(season_id, desc(total_wins)) %>%
    mutate(rank = as.character(rank))

p <- ggplot(wins_most_year) +
    geom_tile(aes(x = rank,
                  y = total_wins/2,
               height = total_wins,
               width = 0.5,
               group = team_name, 
               fill = team_name), alpha = 0.8, color = NA, show.legend = F) +
    geom_text(aes(x = rank, y = 0, label = str_wrap(team_name,15), 
                  color = team_name, group = team_name,
                  size = 2), vjust = 0.2, hjust = 1) +
   # geom_text(aes(x = rank, y = total_wins + 0.5, label = {as.integer(total_wins)}, 
   #               color = team_name, group = team_name,
   #                size = 2)) +
    geom_text(data = wins_most_year %>% select(season_id, season_name) %>% distinct(), 
              aes(y = 1, 
                  x = 9, 
                  label = season_name,
                  group = NA,),
                  size = 6,
              color = "gray30") +
    coord_flip(clip = "off", expand = FALSE) +
    scale_y_continuous(n.breaks = 15) +
    labs(title = "Teams with Most Wins\n", 
         subtitle = "England Football Women's Super League Tier 1\n",
         caption = "Data curated by Rob Clapp",
         x = "", 
         y = "#Matches") +
    theme_minimal(16) +
    theme(legend.position = "none",
          panel.grid = element_blank(),
          axis.line.x = element_line(color = "gray90"),
          axis.text.y = element_blank(),
          plot.margin = margin(2,2, 2, 4, "cm"),
          plot.title=element_text(size=20, hjust=0.5, face="bold", colour="grey20", vjust=-1),
          plot.subtitle=element_text(hjust=0.5, face="italic", colour="grey30", vjust=-1)) +
    transition_states(season_id, transition_length = 5, state_length = 1,
                      wrap = FALSE) +
    view_follow(fixed_y = TRUE)
    
    
animate(p,
         nframes = 200, fps = 20, width = 800, height = 600, renderer = gifski_renderer("gganim.gif"))
```

