---
title: "tt_sep10"
output: html_document
date: "2024-09-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
#library(showtext)
```

```{r}
college_admissions <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-09-10/college_admissions.csv')
```

```{r}
#load font
# Add Google font and enable showtext
# font_add_google(name = "Open Sans", family = "Open Sans")
# showtext_auto()
```

```{r}
tier_income_attend <- college_admissions %>%
    group_by(par_income_lab, tier) %>%
    summarize(
        #apply = sum(apply_unwgt, na.rm = T)#,
        attend_wt = sum(attend), #fraction of test-takers attending the college by tier
        attend_unwt = sum(attend_unwgt)
    ) %>%
ungroup()

# adding an empty row

add_empty_rows <- tier_income_attend %>%
    ungroup() %>%
    select(tier) %>%
    distinct() %>%
    mutate(
        par_income_lab = "",
        attend_unwt = NA_real_,
        attend_wt = NA_real_
    ) %>%
    select(par_income_lab, tier, attend_wt, attend_unwt)

tier_income_attend <- tier_income_attend %>%
    rbind(add_empty_rows)
```


```{r}
# make factor
income_labs <- unique(tier_income_attend$par_income_lab)
income_labs <- c(income_labs[1:13], "", income_labs[14])
tier_income_attend$par_income_lab <-
    factor(tier_income_attend$par_income_lab,
           levels = income_labs)
tier_income_attend$tier <- 
    factor(tier_income_attend$tier,
           levels = c("Selective private", "Selective public", "Highly selective private",
                      "Highly selective public", "Ivy Plus", "Other elite schools (public and private)"),
           labels = c("Selective private", "Selective public", "Highly selective private",
                      "Highly selective public", "Ivy Plus", "Other elite schools"))
```

```{r}
ggplot(tier_income_attend,
       aes(x = par_income_lab, y = fct_rev(tier))) +
    geom_tile(aes(fill = attend_unwt, color = is.na(attend_unwt)), show.legend = F) +
    geom_text(aes(label = round(attend_unwt*100,1),
                  color = attend_unwt > .15),
       show.legend = F)+
    scale_fill_continuous(
        type = "viridis",
        direction = -1,
        na.value = "white"
    )+
    scale_color_manual(
        values = c("gray10", "white")
    )+
    # scale_x_discrete(
    #     position = "top"
    # ) +
    labs(
        x = "Parent Income Percentile",
        y = "",
        title = "Attendance Rates across Selective US Colleges",
        subtitle = "Higher Enrollment Rates for Students from Wealthier Families.\n",
        caption = "Source: Opportunity Insights | College-Level Data for 139 Selective American Colleges"
    ) +
    coord_cartesian(clip = "off", ylim = c(1,6),
                    xlim = c(1, 16))+
    annotate(
        x = -1.3, y = 6.7, geom = "text", label = "Reading the plot:",
        color = "gray10", size = 3.5, fontface = "bold"
    ) +
    annotate(
        x = 0, y = 6.7, geom = "point", shape = 22,
        size = 5, fill = "green4"
    ) +
     annotate(
        x = 0, y = 6.7, geom = "text", label = "n",
        size = 4, color = "azure"
    ) +
     annotate(
        x = 5, y = 6.7, geom = "text", label = "n% of test-takers whose parents are in X income group attended tier Y schools.", color = "gray10", fontface = "italic", lineheight = 0.8,
        size = 3.5
    ) +
    # annotate(
    #      geom = "segment", x = 13.3, y = 7.05, xend = 12.8, yend = 7.05,
    #      arrow = arrow(type = "closed", length = unit(0.02, "npc")), color = "black"
    # ) +
    theme(
        plot.background = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(hjust = 0.3),
        plot.caption = element_text(size = 8),
        text = element_text(size = 12),
        axis.ticks.x = element_blank(),
        axis.title.x = element_text(size = 10, face = "bold"),
        axis.text = element_text(size = 9),
        plot.subtitle = element_text(size = 12, hjust = 0.3)
    )
```

```{r}
ggsave(here::here("products/tt_sep10_college_admission_raw.jpeg"),
       width = 10, height = 5)
```

```{r}
ggplot(tier_income_attend,
       aes(x = par_income_lab, y = fct_rev(tier))) +
    geom_tile(aes(fill = attend_wt, color = is.na(attend_wt)), show.legend = F) +
    geom_text(aes(label = round(attend_wt*100,1),
                  color = attend_wt > .15),
       show.legend = F)+
    scale_fill_continuous(
        type = "viridis",
        direction = -1,
        na.value = "white"
    )+
    scale_color_manual(
        values = c("gray10", "white")
    )+
    # scale_x_discrete(
    #     position = "top"
    # ) +
    labs(
        x = "Parent Income Percentile",
        y = "",
        title = "Test-score-Adjusted Attendance Rates for Selective US Colleges",
        subtitle = "Test Score Differences Explain Some, But Not All, of the College Attendance Gap.\n",
        caption = "Source: Opportunity Insights | College-Level Data for 139 Selective American Colleges"
    ) +
    coord_cartesian(clip = "off", ylim = c(1,6),
                    xlim = c(1, 16))+
    annotate(
        x = -1.3, y = 6.7, geom = "text", label = "Reading the plot:",
        color = "gray10", size = 3.5, fontface = "bold"
    ) +
    annotate(
        x = 0, y = 6.7, geom = "point", shape = 22,
        size = 5, fill = "green4"
    ) +
     annotate(
        x = 0, y = 6.7, geom = "text", label = "n",
        size = 4, color = "azure"
    ) +
     annotate(
        x = 6.5, y = 6.7, geom = "text", label = "n% of test-takers whose parents are in X income group attended tier Y schools, adjusted for test-scores.", color = "gray10", fontface = "italic", lineheight = 0.8,
        size = 3.5
    ) +
    # annotate(
    #      geom = "segment", x = 13.3, y = 7.05, xend = 12.8, yend = 7.05,
    #      arrow = arrow(type = "closed", length = unit(0.02, "npc")), color = "black"
    # ) +
    theme(
        plot.background = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(hjust = 0.3),
        plot.caption = element_text(size = 8),
        text = element_text(size = 14),
        axis.ticks.x = element_blank(),
        axis.title.x = element_text(size = 10, face = "bold"),
        axis.text = element_text(size = 9),
        plot.subtitle = element_text(size = 12, hjust = 0.3)
    )
```


```{r}
ggsave(here::here("products/tt_sep10_college_admission_weighted.jpeg"),
       width = 10, height = 5)
```
