---
title: "tt_sep324"
author: "Havisha Khurana"
date: "2024-09-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
library(tidyr)
library(showtext)
library(ggalluvial)
library(forcats)
library(patchwork)
library(stringr)
```

```{r read data}
qname_levels_single_response_crosswalk <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-09-03/qname_levels_single_response_crosswalk.csv')
stackoverflow_survey_questions <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-09-03/stackoverflow_survey_questions.csv')
stackoverflow_survey_single_response <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-09-03/stackoverflow_survey_single_response.csv')


```

```{r load font}
font_add_google("Open Sans", "os")
showtext_auto()
```

```{r relabel data}
relabel_so <- stackoverflow_survey_single_response %>%
  select(response_id, main_branch, dev_type, ai_threat, ai_complex) %>%
  pivot_longer(
    cols = -response_id,
    names_to = "qname",
    values_to = "level"
  ) %>%
  left_join(qname_levels_single_response_crosswalk) %>%
  select(response_id, qname, label) %>%
  pivot_wider(
    names_from = qname,
    values_from = label
  ) %>%
  # re-categorize
  mutate(
    # Assuming dev_type is a factor or character variable
    dev_type = case_when(
    dev_type %in% c("Academic researcher", "Scientist", "Research & Development role") ~ "Research & Academia",
    dev_type %in% c("Data engineer", "Data or business analyst", "Data scientist or machine learning specialist", "Developer, AI") ~ "Data & AI",
    dev_type %in% c("Developer, back-end", "Developer, desktop or enterprise applications", "Developer, embedded applications or devices",
                    "Developer, front-end", "Developer, full-stack", "Developer, game or graphics",
                    "Developer, mobile", "Developer, QA or test", "Developer, AI", "Blockchain", "Cloud infrastructure engineer") ~ "Development",
    dev_type %in% c("DevOps specialist", "Engineer, site reliability", "System administrator", "Database administrator") ~ "DevOps & Infrastructure",
    dev_type %in% c("Engineering manager", "Hardware Engineer", "Security professional", "Senior Executive (C-Suite, VP, etc.)") ~ "Engineering &\nTechnical Management",
    dev_type %in% c("Product manager", "Project manager") ~ "Product & Project Management",
    dev_type %in% c("Designer", "Developer Experience", "Developer Advocate", "Marketing or sales professional") ~ "Design, Marketing\n& User Experience",
    dev_type %in% c("Educator", "Student") ~ "Education & Training",
    TRUE ~ "Other"
  ),
  main_branch = case_when(
    main_branch %in% c("I am a developer by profession", "I used to be a developer by profession, but no longer am") ~ "Developer",
    main_branch %in% c("I am not primarily a developer, but I write code sometimes as part of my work/studies", 
    "I code primarily as a hobby") ~ "Code for work/hobby",
    main_branch == "I am learning to code" ~ "Learning to Code"
  ),
  main_branch = factor(main_branch, 
                       levels = c("Developer", "Code for work/hobby", "Learning to Code")),
  ai_threat = if_else(ai_threat == "I'm not sure", "Unsure", ai_threat),
  ai_complex = gsub(" at handling complex tasks", "", ai_complex),
  ai_complex = factor(ai_complex,
                      levels = c("Very well", "Good, but not great", "Neither good or bad", "Bad", "Very poor"),
                      labels = c("Very well", "Good,\nbut not great", "Neither good\nor bad", "Bad", "Very poor")),
  ai_threat = factor(ai_threat, levels = c("Yes", "Unsure", "No"))
)
```
```{r}
make_alluvial <- function(df, group_col, outcome_col){
  
  plot <- df %>%
  count({{group_col}}, {{outcome_col}}) %>%
  drop_na() %>%
  group_by({{group_col}}) %>%
  mutate(group_n = sum(n),
         prop_n = n/group_n) %>% 
  ungroup() %>%
  #mutate(across({{outcome}}, ~fct_reorder(.x, prop_n))) %>%
  ggplot() +
  geom_alluvium(aes(axis1 = {{group_col}}, axis2 = {{outcome_col}}, y = prop_n, fill = {{outcome_col}}), 
                width = 1/4)+
  geom_stratum(aes(axis1 = {{group_col}}, axis2 = {{outcome_col}}, y = prop_n, fill = {{outcome_col}}), 
               width = 1/8, alpha = 0.4) +
  geom_text(stat = "stratum", aes(axis1 = {{group_col}}, axis2 = {{outcome_col}}, y = prop_n, label = after_stat(stratum)), 
             size = 6, hjust = 0, nudge_x = 0.08, lineheight = 0.4, family = "os") +
  # geom_text(data = description_text,
  #           aes(x = x_pos, y = y_pos, label = labels), lineheight = 0.6, nudge_y = 2000, family = "os") +
  theme(
    text = element_text(family = "os"),
    plot.title = element_text(hjust = 0),
    plot.background = element_blank(),
    panel.background = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    legend.position = "none",
    axis.title = element_blank()
  )
  
  return(plot)
}
```

```{r}
main_branch_ai_threat <- make_alluvial(relabel_so, main_branch, ai_threat) +
  scale_fill_manual(
    values = c("Yes" = "orange3", "No" = "skyblue3", "Unsure" = "skyblue3")
  )+
  labs(
    title = "Is AI a threat to your job?"
  )+
  xlim(0.9,2.2)

dev_type_ai_threat <- make_alluvial(relabel_so, dev_type, ai_threat) +
  scale_fill_manual(
    values = c("Yes" = "orange3", "No" = "skyblue3", "Unsure" = "skyblue3")
  )+
  labs(
    title = "Is AI a threat to your job?"
  )+
  xlim(0.9,2.2)

main_branch_ai_complex <- make_alluvial(relabel_so, main_branch, ai_complex) +
  scale_fill_manual(
    values = c(rev(RColorBrewer::brewer.pal(5, "PuOr")))
  )+
  labs(
    title = "Is AI good at handling complex tasks?"
  )+
  xlim(0.9,2.4)

dev_type_ai_complex <- make_alluvial(relabel_so, dev_type, ai_complex) +
  scale_fill_manual(
    values = c(rev(RColorBrewer::brewer.pal(5, "PuOr")))
  )+
  labs(
    title = "Is AI good at handling complex tasks?"
  )+
  xlim(0.9,2.4)
```

```{r combine alluvial plot}

main_branch_ai <- main_branch_ai_threat + main_branch_ai_complex +
  #plot_layout(widths = c(4, -1.1 ,4.5)) +
  plot_annotation(
    title = "What people with different coding skills think about AI?",
    subtitle = str_wrap("A larger share of respondents learning to code view AI as a threat to their jobs and believe it effectively handles complex tasks."),
    caption = "Note: Flow shows proportion by coding skills\nSource: Stack OVerflow Annual Developer Survey"
  ) &
  theme(
    text = element_text(size = 20, family = "os"),
    plot.title = element_text(hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5, lineheight = 0.4),
    plot.caption = element_text(lineheight = 0.4),
    plot.background = element_rect(fill = "cornsilk", color = NA),
    panel.grid = element_blank()
  )

dev_type_ai <- dev_type_ai_threat + dev_type_ai_complex +
  #plot_layout(widths = c(4.5, -1.1 ,4.5)) +
  plot_annotation(
    title = "What people in different industries think about AI?",
    subtitle = str_wrap("8-13% of respondents across industries view AI as a threat to their jobs, with divided opinions on its ability to handle complex tasks"),
    caption = "Note: Flow shows proportion by industry\nSource: Stack OVerflow Annual Developer Survey"
  ) &
  theme(
    text = element_text(size = 20, family = "os"),
    plot.title = element_text(hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5, lineheight = 0.4),
    plot.caption = element_text(lineheight = 0.4),
    plot.background = element_rect(fill = "cornsilk", color = NA),
    panel.grid = element_blank()
  )
```

```{r}
ggsave(here::here("products/tt_sep3_main_branch_ai.jpeg"),
       main_branch_ai,
       height = 3.5, width = 5)

ggsave(here::here("products/tt_sep3_dev_type_ai.jpeg"),
       dev_type_ai,
       height = 4, width = 5)
```

